language: generic
sudo: required
services:
  - docker
#create an image to test react app (assuming I have test to run before deploying)
before_install:
  - docker build -t hishamss/go-meeting-react-test -f ./client/Dockerfile.dev ./client
#run the image to create container, and if the test existed with 0, that means it passed the test
script:
  - docker run -e CI=true hishamss/go-meeting-react-test npm test -- --coverage

#create images for deployment
after_success:
  - docker build -t hishamss/go-meeting-client ./client
  - docker build -t hishamss/go-meeting-api ./api
  - docker build -t hishamss/go-meeting-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push hishamss/go-meeting-client
  - docker push hishamss/go-meeting-api
  - docker push hishamss/go-meeting-nginx
